apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # PostgreSQL configuration file for Kubernetes
    listen_addresses = '*' # Escuchar en todas las IPs
    max_connections = 100
    # SSL Configuration (desactivado para simplificar localmente)
    ssl = off
    #ssl_cert_file = 'server.crt' # Comentado, ya que SSL está off
    #ssl_key_file = 'server.key'  # Comentado, ya que SSL está off
    password_encryption = md5 # Usar MD5 para la contraseña

    # Logging
    log_connections = on
    log_disconnections = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_line_prefix = '%m [%p] %q%u@%d '
    log_timezone = 'UTC'

    # Resource usage (basic tuning)
    shared_buffers = 128MB
    effective_cache_size = 512MB

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    # Regla por defecto para localhost (dentro del pod)
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 scram-sha-256

    # Permite conexiones desde cualquier IP interna de K8s sin SSL (para simplificar)
    host    all             all             0.0.0.0/0               md5

    # OPCIONAL: Si quisieras requerir SSL para alguna conexión, sería así:
    hostssl criptodb        admincar        0.0.0.0/0               md5